name: 'docker-metanorma-run'
description: 'Composite action which help to install custom/private flavors'
inputs:
  extra-flavors:
    description: 'Space separated list of extra flavor extensions'
    default: ''
  github-pakages-token:
    description: 'GitHub token to access '
    default: ''

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        apt-get update -y && apt-get install -y gcc g++ ruby-dev

        if [ "${{ inputs.github-pakages-token }}" != "" ]; then
          curl -L --retry 3 https://raw.githubusercontent.com/metanorma/ci/main/gh-rubygems-setup-action/gen-gemrc-for-gh-packages.sh | bash -s -- "${{ inputs.github-pakages-token }}"
          curl -L --retry 3 https://raw.githubusercontent.com/metanorma/ci/main/gh-rubygems-setup-action/gen-bundle-config-for-gh-packages.sh | bash -s -- "${{ inputs.github-pakages-token }}" metanorma --global
        fi

        file ~/.bundle/config
        file ~/.gemrc

        for flavor in ${{ inputs.extra-flavors }}; do
          bundle add metanorma-${flavor}
        done
