name: metanorma-new
description: composite action which help to run metanorma site generate
inputs:
  type:
    description: Document type
    required: true
  doctype:
    description: Metanorma doctype
    required: true
  output-path:
    description: Directory to put generated document
    default: '.'
  overwrite:
    description: Overwrite existing document
    default: '' # false
  no-progress:
    description: Don't show progress for long running tasks (like download)
    default: 'true'
  template:
    description: Git hosted remote or local FS template skeleton
    default: '' # false
  use-bundler:
    description: 'Run in bundler'
    default: '' # false
  ensure-manifest:
    description: 'Generate minimal metanorma.yml manifest if missing'
    default: '' # false

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        ${{ inputs.use-bundler && 'bundle exec' || '' }}            \
            metanorma new ${{ inputs.output-path }}                 \
            -t ${{ inputs.type }}                                   \
            -d ${{ inputs.doctype }}                                \
            ${{ inputs.overwrite && '--' || '--no-' }}overwrite     \
            ${{ inputs.no-progress && '--' || '--no-' }}no-progress \
            ${{ inputs.template && format('-l {0}', inputs.template) || '' }}

    - shell: bash
      run: |
        if [ ! -f ${{ inputs.output-path }}/metanorma.yml -a "${{ inputs.output-path }}" = "true" ]; then
          cat << 'EOF' > ${{ inputs.output-path }}/metanorma.yml
        metanorma:
          source:
            files:
              - document.adoc
        EOF
          echo "${{ inputs.output-path }}/metanorma.yml generated."
        fi
        

