name: metanorma-collection
description: Render HTML pages from XML/YAML colection
inputs:
  manifest:
    description: Metanorma collection mainfest file
    required: true
  cover-page:
    description: Liquid template
    required: true
  output-dir:
    description: Directory to save compiled files
    default: '.'
  formats:
    description: Formats to generate
    required: false
  agree-to-terms:
    description: 'Agree / Disagree with all third-party licensing terms presented (WARNING: do know what you are agreeing with!)'
    default: '' # false
  install-fonts:
    description: 'To allow skip the font installation process'
    default: 'true'
  continue-without-fonts:
    description: 'Continue processing even when fonts are missing'
    default: '' # false
  no-progress:
    description: Don't show progress for long running tasks (like download)
    default: 'true'
  use-bundler:
    description: 'Run in bundler'
    default: '' # false

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        ${{ inputs.use-bundler && 'bundle exec' || '' }}                                  \
            metanorma collection ${{ inputs.manifest }} -w ${{ inputs.output-dir }}       \
            ${{ inputs.formats && format('-x {0}', inputs.formats) || '' }}               \
            -c ${{ inputs.cover-page }}                                                   \
            ${{ inputs.agree-to-terms && '--' || '--no-' }}agree-to-terms                 \
            ${{ inputs.continue-without-fonts && '--' || '--no-' }}continue-without-fonts \
            ${{ inputs.install-fonts && '--' || '--no-' }}install-fonts                   \
            ${{ inputs.no-progress == 'true' && '--no-' || '' }}progress
