name: test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-native:
    name: Test ${{ matrix.action }} action on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        action:
        # - ./site-gen/
        # - ./docker-site-gen/
        - actions-mn/cli/site-gen@main
        # - actions-mn/cli/site-gen@${{ github.head_ref }}
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
    - uses: actions/checkout@v2

    - uses: actions/checkout@v2
      with:
        repository: metanorma/mn-samples-iso
        path: iso

    - run: echo "${{ matrix.action }}"

    - uses: actions-mn/setup@master

    - uses: ${{ matrix.action }}
      with:
        source-path: iso
        config-file: iso/metanorma.yml
        agree-to-terms: true

    - uses: andstor/file-existence-action@v1
      with:
        files: site/index.html
