name: test

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref_name }}'
  cancel-in-progress: true

jobs:
  test-new:
    name: Test actions-mn/cli/new action on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
    - uses: actions/checkout@v3

    - uses: actions-mn/setup@main

    - uses: ./new/
      with:
        type: iso
        doctype: international-standard
        output-path: test

    - uses: ./new/
      with:
        type: iso
        doctype: international-standard
        template: https://github.com/metanorma/mn-templates-iso
        output-path: test-git

    - uses: andstor/file-existence-action@v1
      with:
        files: test/document.adoc, test/metanorma.yml

  test-setup-flavors:
    name: Test actions-mn/cli/setup-flavors@${{ github.head_ref }} action on ${{ matrix.os }}
    runs-on: ubuntu-latest
    container:
      image: metanorma/metanorma:latest
    strategy:
      fail-fast: false
      matrix:
        flavors:
        - ribose
        - bsi
        - ribose bsi
        - ribose bsi nist
    steps:
    - uses: actions/checkout@v3

    - if: contains(matrix.flavors, 'ribose')
      uses: actions/checkout@v3
      with:
        repository: metanorma/mn-samples-ribose
        path: ribose

    - if: contains(matrix.flavors, 'bsi')
      uses: actions/checkout@v3
      with:
        repository: metanorma/mn-samples-bsi
        path: bsi
        token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}

    - uses: ./setup-flavors
      with:
        extra-flavors: ${{ matrix.flavors }}
        github-pakages-token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}

    - if: contains(matrix.flavors, 'ribose')
      uses: ./site-gen/
      with:
        source-path: ribose
        config-file: metanorma.yml
        agree-to-terms: true

    - if: contains(matrix.flavors, 'bsi')
      uses: ./site-gen/
      with:
        source-path: bsi
        config-file: metanorma.yml
        agree-to-terms: true