name: test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-site-gen-local:
    name: Test ./site-gen/ action on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
    - uses: actions/checkout@v2

    - uses: actions/checkout@v2
      with:
        repository: metanorma/mn-samples-iso
        path: iso

    - uses: actions-mn/setup@master

    - uses: ./site-gen/
      with:
        source-path: iso
        config-file: metanorma.yml
        agree-to-terms: true

    - uses: andstor/file-existence-action@v1
      with:
        files: site/index.html

  test-docker-site-gen-local:
    name: Test ./docker-site-gen/ action on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v2

    - uses: actions/checkout@v2
      with:
        repository: metanorma/mn-samples-iso
        path: iso

    - uses: actions-mn/setup@master

    - uses: ./docker-site-gen/
      with:
        source-path: iso
        config-file: iso/metanorma.yml
        agree-to-terms: true

    - uses: andstor/file-existence-action@v1
      with:
        files: site/index.html

  test-site-gen:
    if: github.head_ref == 'main'
    name: Test actions-mn/cli/site-gen@${{ github.head_ref }} action on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
    - uses: actions/checkout@v2

    - uses: actions/checkout@v2
      with:
        repository: metanorma/mn-samples-iso
        path: iso

    - uses: actions-mn/setup@master

    - uses: actions-mn/cli/site-gen@main # context expression cannot be used instead main
      with:
        source-path: iso
        config-file: metanorma.yml
        agree-to-terms: true

    - uses: andstor/file-existence-action@v1
      with:
        files: site/index.html

  test-docker-site-gen:
    if: github.head_ref == 'main'
    name: Test actions-mn/cli/docker-site-gen@${{ github.head_ref }} action on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v2

    - uses: actions/checkout@v2
      with:
        repository: metanorma/mn-samples-iso
        path: iso

    - uses: actions-mn/setup@master

    - uses: actions-mn/cli/docker-site-gen@main # context expression cannot be used instead main
      with:
        source-path: iso
        config-file: iso/metanorma.yml
        agree-to-terms: true

    - uses: andstor/file-existence-action@v1
      with:
        files: site/index.html

  test-new:
    name: Test actions-mn/cli/new action on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
    - uses: actions/checkout@v2

    - uses: actions-mn/setup@master

    - uses: ./new/
      with:
        type: iso
        doctype: international-standard
        output-path: test

    - uses: ./new/
      with:
        type: iso
        doctype: international-standard
        template: https://github.com/metanorma/mn-templates-iso
        output-path: test-git

    - uses: andstor/file-existence-action@v1
      with:
        files: test/document.adoc, test/metanorma.yml

  test-compile:
    name: Test actions-mn/cli/compile action on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
    - uses: actions/checkout@v2

    - uses: actions-mn/setup@master

    - run: mkdir result1
    - uses: ./compile/
      with:
        input-file: README.adoc
        type: iso
        extensions: html
        output-dir: ./result1
        no-install-fonts: true

    - run: mkdir result2
    - uses: ./compile/
      with:
        input-file: README.adoc
        type: iso
        extensions: doc
        output-dir: result2
        agree-to-terms: true

    - uses: andstor/file-existence-action@v1
      with:
        files: result1/README.html, result2/README.doc

  test-use-bundler:
    name: Test actions-mn/cli actions on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
    - uses: actions/checkout@v2

    - run: |
        echo 'source "https://rubygems.org"' > Gemfile
        echo 'gem "sassc"' >> Gemfile
        echo 'gem "metanorma-cli"' >> Gemfile

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true

    - run: mkdir result
    - uses: ./compile/
      with:
        input-file: README.adoc
        type: iso
        extensions: html
        output-dir: ./result
        no-install-fonts: true
        use-bundler: true

    - uses: ./new/
      with:
        type: iso
        doctype: international-standard
        output-path: test
        use-bundler: true

    - uses: actions/checkout@v2
      with:
        repository: metanorma/mn-samples-iso
        path: iso

    - uses: ./site-gen/
      with:
        source-path: iso
        config-file: metanorma.yml
        agree-to-terms: true
        use-bundler: true
