name: test

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref_name }}'
  cancel-in-progress: true

jobs:
  test-new:
    name: Test actions-mn/cli/new action on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
    - uses: actions/checkout@v3

    - uses: actions-mn/setup@main

    - uses: ./new/
      with:
        type: iso
        doctype: international-standard
        output-path: test

    - uses: ./new/
      with:
        type: iso
        doctype: international-standard
        template: https://github.com/metanorma/mn-templates-iso
        output-path: test-git

    - uses: andstor/file-existence-action@v1
      with:
        files: test/document.adoc, test/metanorma.yml
